#!/bin/bash

script_name=$(basename $0);

source check_tunnel.sh

if [ -z $KATANA_VERSION ];then
	export KATANA_VERSION=4.0v4
fi

if [ -z $KTOA_VERSION ];then
	export KTOA_VERSION=3.2.1.1
fi

if [ -z $RENDERMAN_VERSION ];then
    export RENDERMAN_VERSION=24.2
fi

if [ -z $MAYA_VERSION ];then
	export MAYA_VERSION=2018
fi

if [ -z $MTOA_VERSION ];then
	export MTOA_VERSION=4.1.0
fi

if [ -z $ALSHADERS_VERSION ];then
	export ALSHADERS_VERSION=2.0.0b2
fi

if [ -z $ALSHADERS_LEGACY_VERSION ];then
	export ALSHADERS_LEGACY_VERSION=1.0.0rc20
fi

if [ -z $YETI_VERSION ];then
    export YETI_VERSION=2.2.6
fi

if [ -z $GOLAEM_VERSION ];then
    export GOLAEM_VERSION=6.4
fi

export foundry_LICENSE=4101@localhost
export solidangle_LICENSE=5060@localhost

SW=/home/software
SA_ROOT=$SW/solidangle

# Set Environment Variables for Golaem
export GOLAEM_INSTALL_PATH=$SW/golaem/${GOLAEM_VERSION}/${MAYA_VERSION}
export KATANA_POST_PYTHONPATH=${GOLAEM_INSTALL_PATH}/procedurals/katana/Python

export KATANA_ROOT=$SW/katana/${KATANA_VERSION}/

export KATANA_MIN_MAJ_VERSION=`echo $KATANA_VERSION | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'`

export KTOA_ROOT=$SA_ROOT/ktoa/${KTOA_VERSION}/${KATANA_MIN_MAJ_VERSION}

export RMAN_MAJ_VERSION=`echo $RENDERMAN_VERSION | sed -r 's/^[^0-9]*([0-9]+).*/\1/'`

export RMANTREE="/opt/pixar/RenderManProServer-${RENDERMAN_VERSION}/"
export RMK_ROOT="/opt/pixar/RenderManForKatana-${RENDERMAN_VERSION}/plugins/katana${KATANA_MIN_MAJ_VERSION}"

KATANA_RESOURCES="${KATANA_RESOURCES}:${KTOA_ROOT}"
KATANA_RESOURCES+=":${KTOA_ROOT}/USD/KatanaUsdPlugins/plugin:${KTOA_ROOT}/USD/KatanaUsdArnold"
# KATANA_RESOURCES+=":${GOLAEM_INSTALL_PATH}/procedurals/katana"
KATANA_RESOURCES+=":${RMK_ROOT}"
# KATANA_RESOURCES+=":${KATANA_ROOT}/plugins/Resources/Usd/plugin"
KATANA_POST_PYTHONPATH+=":${KATANA_RESOURCES}"
export KATANA_RESOURCES

FNPXR_PLUGINPATH=${KTOA_ROOT}/USD/Viewport/:${FNPXR_PLUGINPATH}
export FNPXR_PLUGINPATH

PYTHONPATH=${KTOA_ROOT}/USD/KatanaUsdPlugins/lib/python:${PYTHONPATH}
export PYTHONPATH

export peregrinel_LICENSE=5053@china
export YETI_ROOT=${SW}/yeti/${YETI_VERSION}/${MAYA_VERSION}

export PATH=${KTOA_ROOT}/bin:$YETI_ROOT/bin:$KATANA_ROOT:$PATH

export DEFAULT_RENDERER=arnold
export USD_KATANA_ALLOW_CUSTOM_MATERIAL_SCOPES=true


#---------------------

export MANDELBULB_ROOT=/data/Dev/mandlebulb/
export ALSHADERS_ROOT=${SA_ROOT}/alshaders/${ALSHADERS_VERSION}
export ALSHADERS_LEGACY_ROOT=${SA_ROOT}/alshaders/${ALSHADERS_LEGACY_VERSION}
export MTOA_PATH=${SA_ROOT}/mtoa/${MTOA_VERSION}/${MAYA_VERSION}
export MAYA_PATH=/usr/autodesk/maya${MAYA_VERSION}
export XGEN_LOCATION=${MAYA_PATH}/plug-ins/xgen
export BIFROST_ROOT=/usr/autodesk/bifrost

LD_LIBRARY_PATH="${LD_LIBRARY_PATH}"
LD_LIBRARY_PATH+=":${KTOA_ROOT}/USD/KatanaUsdPlugins/lib:${KTOA_ROOT}/USD/KatanaUsdPlugins/plugin/Libs"
LD_LIBRARY_PATH+=":$KATANA_ROOT/plugins/Resources/Usd/lib"
LD_LIBRARY_PATH+=":$KTOA_ROOT/bin:$BIFROST_ROOT/maya${MAYA_VERSION}/lib:$XGEN_LOCATION/lib/:$MAYA_PATH/lib:$MTOA_PATH/bin"
LD_LIBRARY_PATH+=":${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH

ARNOLD_PLUGIN_PATH="$ARNOLD_PLUGIN_PATH"
# ARNOLD_PLUGIN_PATH+=":$MANDELBULB_ROOT"
# ARNOLD_PLUGIN_PATH+=":$ALSHADERS_ROOT/bin"
# ARNOLD_PLUGIN_PATH+=":$ALSHADERS_LEGACY_ROOT/bin"
# ARNOLD_PLUGIN_PATH+=":$YETI_ROOT/bin/pgYetiArnold.so"
# ARNOLD_PLUGIN_PATH+=":$MTOA_PATH/shaders"
# ARNOLD_PLUGIN_PATH+=":$MTOA_PATH/procedurals"
# ARNOLD_PLUGIN_PATH+=":${GOLAEM_INSTALL_PATH}/procedurals:${GOLAEM_INSTALL_PATH}/shaders"
export ARNOLD_PLUGIN_PATH
#--------------------

echo ===================
echo LD_LIBRARY_PATH
echo -e ${LD_LIBRARY_PATH//:/\\n}
echo PATH
echo -e ${PATH//:/\\n}
echo ===================


if [ $script_name == "katana" ];then
    script_name="katanaBin"
fi

export "KATANA_TAGLINE=With KtoA ${KTOA_VERSION}"

exec "${KATANA_ROOT}/bin/$script_name" "$@"

