#!/bin/bash

if [ -z $MAYA_VERSION ];then
	export MAYA_VERSION=2018
fi

if [ -z $MTOA_VERSION ];then
	export MTOA_VERSION=2.1.0
fi

if [ -z $ARNOLD_VERSION ];then
	export ARNOLD_VERSION=5.0.2.0
fi

if [ -z $ALSHADERS_VERSION ];then
	export ALSHADERS_VERSION=2.0.0b2
fi

if [ -z $ALSHADERS_LEGACY_VERSION ];then
	export ALSHADERS_LEGACY_VERSION=1.0.0rc20
fi


SA_ROOT=/opt/solidangle

export MTOA_ROOT=/opt/solidangle/mtoa/${MTOA_VERSION}/${MAYA_VERSION}
export MAYA_LOCATION=/usr/autodesk/maya${MAYA_VERSION}
export ARNOLD_ROOT=/opt/solidangle/arnold/${ARNOLD_VERSION}/

export BIFROST_ROOT=/usr/autodesk/bifrost

export ALSHADERS_ROOT=${SA_ROOT}/alshaders/${ALSHADERS_VERSION}
export ALSHADERS_LEGACY_ROOT=${SA_ROOT}/alshaders/${ALSHADERS_LEGACY_VERSION}

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$BIFROST_ROOT/maya${MAYA_VERSION}/lib:$MAYA_LOCATION/plug-ins/xgen/lib/:$MAYA_LOCATION/lib

# export ARNOLD_PLUGIN_PATH=$MTOA_ROOT:$BIFROST_ROOT/1.5.0/Arnold-5.0.0.0/lib

# export solidangle_LICENSE=5053@localhost
# export ADSKFLEX_LICENSE_FILE=@localhost

echo ===================
echo ARNOLD_PLUGIN_PATH
echo -e ${ARNOLD_PLUGIN_PATH//:/\\n}
echo ===================
echo LD_LIBRARY_PATH
echo -e ${LD_LIBRARY_PATH//:/\\n}

echo $ARNOLD_ROOT

exec "${ARNOLD_ROOT}/bin/kick" -l $MTOA_ROOT/shaders -l $MTOA_ROOT/procedurals -l $BIFROST_ROOT/1.5.0/Arnold-5.0.0.0/lib -l $ALSHADERS_ROOT/bin -l $ALSHADERS_LEGACY_ROOT/bin "$@"

