#!/bin/bash

script_name=$(basename $0);

if [ -z $MAYA_VERSION ];then
	export MAYA_VERSION=2018
fi

if [ -z $MTOA_VERSION ];then
	export MTOA_VERSION=3.1.0.1
fi

if [ -z $C4DTOA_VERSION ];then
    export C4DTOA_VERSION=2.3.0.1
fi

if [ -z $ARNOLD_VERSION ];then
	export ARNOLD_VERSION=5.2.0.1
fi

if [ -z $ALSHADERS_VERSION ];then
	export ALSHADERS_VERSION=2.0.0b2
fi

if [ -z $JSNOISE_VERSION ];then
    export JSNOISE_VERSION=02102017
fi

if [ -z $ALSHADERS_LEGACY_VERSION ];then
	export ALSHADERS_LEGACY_VERSION=1.0.0rc20
fi

if [ -z $ALEMBIC_VERSION ];then
	export ALEMBIC_VERSION=1.7.4
fi

if [ -z $BBALEMBIC_VERSION ];then
	export BBALEMBIC_VERSION=2.0.0
fi

if [ -z $YETI_VERSION ];then
    export YETI_VERSION=2.2.6
fi

if [ -z $GOLAEM_VERSION ];then
    export GOLAEM_VERSION=6.3
fi

export SW=/software

SA_ROOT=$SW/solidangle

export MTOA_ROOT=/opt/solidangle/mtoa/${MTOA_VERSION}/${MAYA_VERSION}
export MAYA_LOCATION=/usr/autodesk/maya${MAYA_VERSION}
export ARNOLD_ROOT=/opt/solidangle/arnold/${ARNOLD_VERSION}
export C4DTOA_ROOT=/opt/solidangle/c4dtoa/${C4DTOA_VERSION}

export peregrinel_LICENSE=5053@china
export YETI_ROOT=${SW}/yeti/${YETI_VERSION}/${MAYA_VERSION}

export BB_ALEMBIC_ROOT=${SW}/bb_alembic/${BBALEMBIC_VERSION}

export BIFROST_ROOT=/usr/autodesk/bifrost

export GOLAEM_ROOT=/software/golaem/${GOLAEM_VERSION}/${MAYA_VERSION}

export ALSHADERS_ROOT=${SA_ROOT}/alshaders/${ALSHADERS_VERSION}
export ALSHADERS_LEGACY_ROOT=${SA_ROOT}/alshaders/${ALSHADERS_LEGACY_VERSION}

export JSNOISE_ROOT=${SA_ROOT}/jsnoise/${JSNOISE_VERSION}

export BOOST_ROOT=$SW/boost/1.59.0
export ILMBASE_ROOT=$SW/openexr/2.2.0
export OPENEXR_ROOT=$SW/openexr/2.2.0
export ALEMBIC_ROOT=$SW/alembic/$ALEMBIC_VERSION

LD_LIBRARY_PATH=$LD_LIBRARY_PATH
LD_LIBRARY_PATH+=:$BIFROST_ROOT/maya${MAYA_VERSION}/lib
LD_LIBRARY_PATH+=:$MAYA_LOCATION/plug-ins/xgen/lib/
LD_LIBRARY_PATH+=:$MAYA_LOCATION/lib
LD_LIBRARY_PATH+=:$BOOST_ROOT/lib
LD_LIBRARY_PATH+=:$ILMBASE_ROOT/lib
LD_LIBRARY_PATH+=:$OPENEXR_ROOT/lib
LD_LIBRARY_PATH+=:$ALEMBIC_ROOT/lib
LD_LIBRARY_PATH+=:$GOLAEM_ROOT/bin

export LD_LIBRARY_PATH

# export ARNOLD_PLUGIN_PATH=$MTOA_ROOT:$BIFROST_ROOT/1.5.0/Arnold-5.0.0.0/lib
ARNOLD_PLUGIN_PATH=$ARNOLD_PLUGIN_PATH:$MTOA_ROOT/shaders
ARNOLD_PLUGIN_PATH+=:$MTOA_ROOT/procedurals
ARNOLD_PLUGIN_PATH+=:$MTOA_ROOT/plugins
ARNOLD_PLUGIN_PATH+=:$C4DTOA_ROOT/shaders
ARNOLD_PLUGIN_PATH+=:$BIFROST_ROOT/1.5.0/Arnold-5.0.0.0/lib
ARNOLD_PLUGIN_PATH+=:$BB_ALEMBIC_ROOT/arnold/procedurals/
# ARNOLD_PLUGIN_PATH+=:$ALSHADERS_ROOT/bin
ARNOLD_PLUGIN_PATH+=:$ALSHADERS_LEGACY_ROOT/bin
ARNOLD_PLUGIN_PATH+=:$JSNOISE_ROOT/bin
ARNOLD_PLUGIN_PATH+=:$GOLAEM_ROOT/procedurals/glmCrowdArnoldPlugin.so:$GOLAEM_ROOT/shaders
export ARNOLD_PLUGIN_PATH
# export solidangle_LICENSE=5053@localhost
# export ADSKFLEX_LICENSE_FILE=@localhost

echo ===================
echo ARNOLD_PLUGIN_PATH
echo -e ${ARNOLD_PLUGIN_PATH//:/\\n}
echo ===================
echo LD_LIBRARY_PATH
echo -e ${LD_LIBRARY_PATH//:/\\n}
echo ===================

echo $ARNOLD_ROOT

if [ $script_name == "kick" ];then
    args="-l $YETI_ROOT/bin/pgYetiArnold.so"
fi

# exec "${ARNOLD_ROOT}/bin/$script_name" -l $MTOA_ROOT/shaders -l $MTOA_ROOT/procedurals -l $BIFROST_ROOT/1.5.0/Arnold-5.0.0.0/lib -l $BB_ALEMBIC_ROOT/arnold/procedurals -l $ALSHADERS_ROOT/bin -l $ALSHADERS_LEGACY_ROOT/bin "$@"
eval "${ARNOLD_ROOT}/bin/$script_name" $args "$@";
exitstatus="$?"
echo "Exit status is $exitstatus"
exit $exitstatus
# exec "${MTOA_ROOT}/bin/$script_name" $args "$@"

