#!/bin/bash

source check_tunnel.sh

if [ -z $NUKE_VERSION ];then
	export NUKE_VERSION=13.0v1
fi

export foundry_LICENSE=4101@localhost 

export PIPELINE=/data/pipeline/nuke

# export NUKE_PATH=${PIPELINE}/common/cryptomatte

export NUKE_ROOT=/home/software/nuke/${NUKE_VERSION}/

export NUKE_MIN_MAJ_VERSION=`echo $NUKE_VERSION | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'`

exec "${NUKE_ROOT}/Nuke$NUKE_MIN_MAJ_VERSION" $@

