#!/bin/bash


script_name=$(basename $0);

if [ -z $OCIO_VERSION ];then
	export OCIO_VERSION=1.0.9
fi

if [ -z $OIIO_VERSION ];then
	export OIIO_VERSION=1.8.5
fi

export SOFTWARE=/home/software

export OCIO_ROOT=$SOFTWARE/ocio/${OCIO_VERSION}
export OIIO_ROOT=$SOFTWARE/oiio/${OIIO_VERSION}

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OCIO_ROOT/lib:$OIIO_ROOT/lib

exec "${OIIO_ROOT}/bin/$script_name" "$@"

