#!/bin/bash

script_name=$(basename $0);

if [ -z $OVDB_VERSION ];then
	export OVDB_VERSION=5.0.0
fi

SW=/software

OVDB_ROOT=/software/openvdb/${OVDB_VERSION}

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SW/openexr/2.2.0/lib:$SW/boost/1.59.0/lib:$OVDB_ROOT/lib

exec "${OVDB_ROOT}/bin/$script_name" "$@"

